### ISSUE TITLE
DuplicateTransitGatewayAttachment error received on 1 of 3 subnets 

### ISSUE THREAD

**Issue by roger-reed** [awslabs/serverless-transit-network-orchestrator#1]
I create three subnets exactly the same way through CloudFormation and consistently 1 of the 3 is not being attached even though tag Attach-to-tgw is present.  The error tag is showing the following:

STNOStatus-Subnet-Error | 2020-01-31T03:22:19Z: An error occurred (DuplicateTransitGatewayAttachment) when calling the CreateTransitGatewayVpcAttachment operation: tgw-04e93f5458d6a0662 has non-deleted Transit Gateway Attachments with same VPC ID.

**Comment by groverlalit** [comment]
Hello Roger, 
Thanks for reporting this issue. We have added this issue to our backlog.

**Comment by naslanidis** [comment]
Hi,

I am seeing the exact same behaviour: 

"An error occurred (DuplicateTransitGatewayAttachment) when calling the CreateTransitGatewayVpcAttachment operation: tgw-003ded20995f40ef3 has non-deleted Transit Gateway Attachments with same VPC ID.",

I have 3 subnets and only 2 of them will attach. I thought this might be related to AZ ID's being different across different accounts but I'm not so sure.  It seems that it's trying to create the attachment instead of adding additional subnets to an existing attachments. 

Is this project still active and being worked on? 

Thanks

**Comment by rakshb** [comment]
Hello @naslanidis. Thanks for the note. This issue will be fixed in the next release of STNO planned for Q3 2020

**Comment by naslanidis** [comment]
> Hello @naslanidis. Thanks for the note. This issue will be fixed in the next release of STNO planned for Q3 2020

Hi, thanks that's great news. 

I've actually worked around it by simply adding a catch to some of the states in the state machine that were sometimes failing and just routing the flow back up top to retry again.  Not perfect but it works and I look forward to seeing the next version.

**Comment by adamcousins** [comment]
@naslanidis 
can you share your workaround?
im hitting this same error and have added 15 retry attempts on the step: TGW Attachment CRUD Operations and some other failing steps however one remaining subnet never gets the attachment after 15 retries.

@rakshb 
Any way to get access to the fix for this in a beta version or similar?

**Comment by bebych** [comment]
> @naslanidis
> can you share your workaround?
> im hitting this same error and have added 15 retry attempts on the step: TGW Attachment CRUD Operations and some other failing steps however one remaining subnet never gets the attachment after 15 retries.
> 
> @rakshb
> Any way to get access to the fix for this in a beta version or similar?

I have also faced this issue. I have added dependency (DependsOn) in order to create subnets one by one and not to confuse STNO
First of all I create subnet-A with tag (Attach-to-tgw),  subnet-B DependsOn subnet-A,  subnet-C  DependsOn subnet-B, etc

**Comment by naslanidis** [comment]
Hi @bebych and @adamcousins 

Initially I played around with the STNO lambda to work around this but then I decided I'd rather not make changes there if a new version will be coming soon. So instead I just added some retries / catches in the state machine spec.  You can replace the original state machine json spec with the attached in the stno hub cfn and it should work. I haven't changed anything else. If there's an error or 'IncorrectState' response it simply restarts from the describe states at the start. It's not pretty, but given a new version should be coming I wanted to keep changes to a minimum. I

[state_machine_spec.txt](https://github.com/awslabs/serverless-transit-network-orchestrator/files/4965003/state_machine_spec.txt)

I've attached a diff output compared to the original spec so you can see what's changed. 

[state_machine_spec_diff.txt](https://github.com/awslabs/serverless-transit-network-orchestrator/files/4965067/state_machine_spec_diff.txt)

**Comment by dougireton** [comment]
I've hit this same issue.

**Comment by sreejanigit** [comment]
If we try to attach a transit gateway to two subnets of the same availability zone, this error occurs. According to the rule , one transit gateway can attach to a subnet of one availability zone only. Please correct me if I am wrong

**Comment by groverlalit** [comment]
@sreejanigit This issue is related to duplicate TGW Attachment (_**DuplicateTransitGatewayAttachment**_) due to a race condition if more than 2 subnets are tagged at the same exact time (example: using CFN template). 
If we try to attach a transit gateway to two subnets in the same availability zone we should expect **_DuplicateSubnetsInSameZoneError_** exception.

**Comment by sreejanigit** [comment]
@groverlalit, sorry for my misunderstanding. Thanks much for correcting me.

**Comment by badaldavda8** [comment]
Is this resolved yet? I am facing this constantly while creating VPC using CFN. I tried adding DependsOn, but it would still fail most of the times with __"errorMessage": "An error occurred (Resource.AlreadyAssociated) when calling the AssociateTransitGatewayRouteTable operation: Transit Gateway Attachment..."__

Or InvalidState error message.

**Comment by adamcousins** [comment]
@groverlalit  is this project abandoned or will bugs like this be resolved in a timely fashion?

**Comment by rayjanoka** [comment]
same issue - what's up @groverlalit? Any word on that new release?

**Comment by rayjanoka** [comment]
the @naslanidis fix seemed to work for me

**Comment by markymarkus** [comment]
Yes, issue is still exists. Fresh install of v2.0.0. Trying to create VPC with 3 subnets from Cloudformation:

Step Functions:
First subnet succeeded.

Second subnet: "errorMessage": "An error occurred (IncorrectState) when calling the AssociateTransitGatewayRouteTable operation: tgw-attach-0a123456789abcdefg is in invalid state",

Third subnet: "errorMessage": "An error occurred (Resource.AlreadyAssociated) when calling the AssociateTransitGatewayRouteTable operation: Transit Gateway Attachment tgw-attach-0a123456789abcdefg is already associated to a route table.",

**Comment by gsingh04** [comment]
We are currently working on the fix. This issue will be addressed in the next release. Please continue to monitor this thread for updates.

**Comment by rakshb** [comment]
We have fixed this issues in V3.0.0 which released this week.
